#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TecDemo.Android.Resource", IsApplication=true)]

namespace TecDemo.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ae = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int af = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ag = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int al = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int am = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ao = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int at = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int au = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int az = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ba = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bb = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bd = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int be = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bf = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bh = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bi = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bj = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bn = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int br = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bs = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bt = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bw = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int by = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bz = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ca = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int cd = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int cf = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int cg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ch = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ci = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int cl = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int cm = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int cn = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int co = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int cr = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int cu = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int cv = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int cy = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int cz = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int de = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int dj = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int dk = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int dm = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int dz = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ec = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ee = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int eg = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int eh = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int er = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int es = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int et = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int eu = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int fi = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int fj = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int fm = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int fr = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ga = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int gb = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int gd = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ge = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int gh = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int gm = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int gn = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int gq = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int gr = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int gt = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int gw = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int gy = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int hk = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int hn = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int hr = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ht = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int hu = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int id = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ie = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int il = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int @in = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int iq = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ir = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int @is = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int it = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int jm = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int jo = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int jp = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int ke = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int kg = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int kh = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int ki = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int km = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int kn = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int kp = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int kr = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int ks = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int kw = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int kz = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int la = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int Launcher = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int lb = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int lc = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int li = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int lk = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int lr = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int ls = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int lt = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int lu = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int lv = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int ly = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int ma = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int mc = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int md = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int me = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int mg = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int mh = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int mk = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int ml = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int mm = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int mn = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int mr = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int mt = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int mu = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int mv = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int mw = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int mx = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int my = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int mz = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int na = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int ne = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int ng = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int ni = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int nl = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int no = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int np = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int nr = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int nz = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int om = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int pa = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int pe = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int pg = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int ph = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int pk = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int pl = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int pt = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int pw = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int py = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int qa = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int ro = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int rs = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int ru = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int rw = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int sa = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int sb = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int sc = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int sd = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int se = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int sg = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int si = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int sk = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int sl = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int sm = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int sn = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int so = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int sr = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int st = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int sv = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int sy = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int sz = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int td = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int tg = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int th = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int tj = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int tl = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int tm = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int tn = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int to = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int tr = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int tt = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int tv = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int tw = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int tz = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int ua = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int ug = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int us = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int uy = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int uz = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int va = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int vc = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int ve = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int vn = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int vu = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int ws = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int ye = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int za = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int zm = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int zw = 2130837701;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
